services:
  notary_url: "http://notary-service.build.10gen.cc:5000"

templates:
  deb:
    org: |
      Origin: merizodb
      Label: merizodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/merizodb-org
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MerizoDB packages
    enterprise: |
      Origin: merizodb
      Label: merizodb
      Suite: {{ .CodeName }}
      Codename: {{ .CodeName }}/merizodb-enterprise
      Architectures: {{ .Architectures }}
      Components: {{ .Component }}
      Description: MerizoDB packages
  index_page: |
    <!DOCTYPE html>
    <html>
     <head>
       <title>{{ .Title }}</title>
     </head>

     <body>
       <table>
        <tr><td>
          <h1>{{ .Title }}</h1>
        </td></tr>

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <a href='..'>Parent Directory</a>
        </td></tr>

        {{ range $fn := .Files }}
        <tr><td>
          <a href='{{ $fn }}'>{{ $fn }}</a>
        </td></tr>
        {{ end }}

        <tr><td>
          <hr>
        </td></tr>

        <tr><td>
          <address>{{ .RepoName }}</address>
        </td></tr>
      </table>
     </body>
    </html>


repos:

####################
#
# Community Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/redhat/6/merizodb-org
      - yum/redhat/6Server/merizodb-org

  - name: rhel67
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/redhat/6/merizodb-org
      - yum/redhat/6Server/merizodb-org

  - name: rhel70
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/redhat/7/merizodb-org
      - yum/redhat/7Server/merizodb-org

  - name: rhel72
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/redhat/7/merizodb-org
      - yum/redhat/7Server/merizodb-org

  - name: amazon
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/amazon/2013.03/merizodb-org

  - name: amazon2
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - yum/amazon/2/merizodb-org

  - name: suse11
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - zypper/suse/11/merizodb-org

  - name: suse12
    type: rpm
    edition: org
    bucket: repo.merizodb.org
    repos:
      - zypper/suse/12/merizodb-org

  - name: debian81
    type: deb
    code_name: "jessie"
    bucket: repo.merizodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/jessie/merizodb-org

  - name: debian92
    type: deb
    code_name: "stretch"
    bucket: repo.merizodb.org
    edition: org
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/stretch/merizodb-org

  - name: debian71
    type: deb
    code_name: "wheezy"
    bucket: repo.merizodb.org
    edition: org
    component: main
    architectures:
      - amd64
      - i386
    repos:
      - apt/debian/dists/wheezy/merizodb-org

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: org
    bucket: repo.merizodb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/precise/merizodb-org

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: org
    bucket: repo.merizodb.org
    component: multiverse
    architectures:
      - amd64
      - i386
    repos:
      - apt/ubuntu/dists/trusty/merizodb-org

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: org
    bucket: repo.merizodb.org
    component: multiverse
    architectures:
      - amd64
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/merizodb-org

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: org
    bucket: repo.merizodb.org
    component: multiverse
    architectures:
      - amd64
      - i386
      - s390x
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/merizodb-org

####################
#
# Enterprise Repos:
#
####################

  - name: rhel62
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/redhat/6/merizodb-enterprise
      - yum/redhat/6Server/merizodb-enterprise

  - name: rhel67
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/redhat/6/merizodb-enterprise
      - yum/redhat/6Server/merizodb-enterprise

  - name: rhel70
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/redhat/7/merizodb-enterprise
      - yum/redhat/7Server/merizodb-enterprise

  - name: rhel71
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/redhat/7/merizodb-enterprise
      - yum/redhat/7Server/merizodb-enterprise

  - name: rhel72
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/redhat/7/merizodb-enterprise
      - yum/redhat/7Server/merizodb-enterprise

  - name: amazon
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/amazon/2013.03/merizodb-enterprise

  - name: amazon2
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - yum/amazon/2/merizodb-enterprise

  - name: suse11
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - zypper/suse/11/merizodb-enterprise

  - name: suse12
    type: rpm
    edition: enterprise
    bucket: repo.merizodb.com
    repos:
      - zypper/suse/12/merizodb-enterprise

  - name: debian92
    type: deb
    edition: enterprise
    code_name: "stretch"
    bucket: repo.merizodb.com
    component: main
    architectures:
      - amd64
    repos:
      - apt/debian/dists/stretch/merizodb-enterprise

  - name: debian81
    type: deb
    edition: enterprise
    code_name: "jessie"
    bucket: repo.merizodb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/jessie/merizodb-enterprise

  - name: debian71
    type: deb
    code_name: "wheezy"
    edition: enterprise
    bucket: repo.merizodb.com
    component: main
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/debian/dists/wheezy/merizodb-enterprise

  - name: ubuntu1204
    type: deb
    code_name: "precise"
    edition: enterprise
    bucket: repo.merizodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/precise/merizodb-enterprise

  - name: ubuntu1404
    type: deb
    code_name: "trusty"
    edition: enterprise
    bucket: repo.merizodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - i386
    repos:
      - apt/ubuntu/dists/trusty/merizodb-enterprise

  - name: ubuntu1604
    type: deb
    code_name: "xenial"
    edition: enterprise
    bucket: repo.merizodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - s390x
      - arm64
      - i386
    repos:
      - apt/ubuntu/dists/xenial/merizodb-enterprise

  - name: ubuntu1804
    type: deb
    code_name: "bionic"
    edition: enterprise
    bucket: repo.merizodb.com
    component: multiverse
    architectures:
      - amd64
      - ppc64el
      - i386
      - s390x
      - arm64
    repos:
      - apt/ubuntu/dists/bionic/merizodb-enterprise
